### ISSUE TITLE
Probar sistemas de compañeros

### ISSUE THREAD

**Issue by STiago** [STiago/Lecrin_Bot#10]

**Comment by pmmre** [comment]
He comprobado el provisionamiento de Chef y funciona perfectamente
![imagen](https://cloud.githubusercontent.com/assets/14886093/20636980/ebba6e86-b378-11e6-9857-fd974dc06b1e.png)

**Comment by pmmre** [comment]
Para comprobar el provisionamiento con ansible lo he configurado poniendo los parámetros de mi máquina.
![imagen](https://cloud.githubusercontent.com/assets/14886093/20637046/71540b6e-b37a-11e6-8386-1f133ddd668f.png)
