### ISSUE TITLE
Orquestar máquinas virtuales provisionando con Ansible

### ISSUE THREAD

**Issue by STiago** [STiago/Lecrin_Bot#12]

**Comment by pmmre** [comment]
He comprobado que efectivamente crea la máquina virtual correctamente.
![imagen](https://cloud.githubusercontent.com/assets/14886093/21161547/588a0c60-c189-11e6-8ce4-7e15a0deb48b.png)

Y que provisona correctamente.
![imagen](https://cloud.githubusercontent.com/assets/14886093/21161604/8104458e-c189-11e6-9e0a-f395cff29ef4.png)
